#! /usr/bin/sh
# cmdline utilities
alias cls="clear"
alias trash="gio trash"
alias rm="trash"
alias merge="paste"
alias grep="grep --color=auto"
alias open="xdg-open"
alias sch="search"
alias ia="search --chat"
alias ai="ia"
alias google="search --google"
alias youtube="search --youtube"

# Default programs substitution
alias mic="micro"
alias nano="nvim"
alias ls="cls && lsd"
alias cl="cs -l"
alias ca="cs -A"
alias cla="cs -lA"
alias ct="cs --tree"
alias cta="cs -A --tree"
alias cat="bat --theme='Everforest Dark'"
alias ll="ls -l"
alias la="ls -A"
alias lla="ls -lA"
alias lt="ls --tree"
alias lta="ls -A --tree"
# Python and julia shortcuts.
alias python="cls && python3"
alias julia="cls && julia"

# Only in kitty terminal (image cat and ssh integration)
alias icat='kitten icat'
alias ssh="kitten ssh"

# Useless stuff
alias fastfetch="cls && fastfetch"
alias neofetch="fastfetch"
#alias pipes="pipes.sh -c 1 -c 2 -c 3 -c 4 -c 5 -c 6 -c 7"
#alias matrix="cmatrix -s"
alias tron="ssh sshtron.zachlatta.com"

